---
- name: Install BIND
  apt:
    name: "{{ bind_package }}"
    default_release: "{{ bind_default_release }}"
    state: present
  notify:
    - Configure BIND service

- name: Create main BIND configuration file
  template:
    src: "{{ bind_conf_template }}"
    dest: "{{ bind_conf_file }}"
    owner: root
    group: bind
    mode: 0644
    validate: named-checkconf "%s"
  notify:
    - Reload BIND

- name: Create BIND options file
  template:
    src: "{{ bind_options_template }}"
    dest: "{{ bind_options_file }}"
    owner: root
    group: bind
    mode: 0644
    validate: named-checkconf "%s"
  notify:
    - Reload BIND

- name: Create BIND zones directory
  file:
    path: "{{ bind_zones_dir }}"
    state: directory
    owner: root
    group: bind
    mode: u=rwx,g=rxs,o=rx

- name: Create BIND zones
  copy:
    content: "{{ item.1 }}"
    dest: "{{ bind_zones_dir }}/{{ item.0 }}"
    owner: root
    group: bind
    mode: 0644
    validate: named-checkzone "{{ item.0 }}" "%s"
  vars:
    current_zone: "{{ item.0 }}"
  loop: "{{ bind_zones|dictsort }}"
  notify:
    - Reload BIND
