---
- name: Start BIND
  service:
    name: "{{ bind_service }}"
    state: "{{ bind_state }}"
    enabled: "{{ bind_enabled }}"

- name: Reload BIND
  service:
    name: "{{ bind_service }}"
    state: reloaded
  when: bind_state != "stopped"
